apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/deployment.yaml
  - base/service.yaml

images:
  - name: zmsdlfsktdma/miniproject
    newTag: "389b8060eb09182e325e2314bbcbb45de4880466"

