apiVersion: v1
kind: Service
metadata:
  name: miniproject
  labels:
    app: miniproject
spec:
  type: NodePort          # 내부 테스트면 ClusterIP로 바꿔도 됨
  selector:
    app: miniproject
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050     # 외부에서 접근 시 http://<노드IP>:30050

