name: CI Smoke - DockerHub login & push

on:
  workflow_dispatch:  # 수동 실행만

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets presence (won't print values)
        shell: bash
        env:
          DU: ${{ secrets.DOCKERHUBUSERNAME }}
          DT: ${{ secrets.DOCKERHUBTOKEN }}
        run: |
          set -euxo pipefail
          [ -n "${DU:-}" ] && echo "DOCKERHUBUSERNAME is SET" || (echo "DOCKERHUBUSERNAME is EMPTY"; exit 2)
          [ -n "${DT:-}" ] && echo "DOCKERHUBTOKEN is SET"    || (echo "DOCKERHUBTOKEN is EMPTY"; exit 2)

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUBTOKEN }} | docker login -u ${{ secrets.DOCKERHUBUSERNAME }} --password-stdin

      - name: Pull base image
        run: docker pull alpine:3.19

      - name: Tag for your repo
        run: docker tag alpine:3.19 ${{ secrets.DOCKERHUBUSERNAME }}/miniproject:smoke-${{ github.run_id }}

      - name: Push test tag
        run: docker push ${{ secrets.DOCKERHUBUSERNAME }}/miniproject:smoke-${{ github.run_id }}

