name: CI - Test, SonarQube, and Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps (prod + dev)
        run: |
          pip install -r app/requirements.txt
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run tests with coverage
        run: |
          pytest app/tests/ --maxfail=1 --disable-warnings --cov=app --cov-report xml

      # ✅ 공식 SonarQube 액션 사용 (별도 설치 불필요)
      # 주의: 아래 URL이 GitHub 러너에서 접근 가능한 공인 IP/도메인이어야 함
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
          SONAR_HOST_URL: http://192.168.10.10:9000
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=miniproject
            -Dsonar.sources=app
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUBTOKEN }} | docker login -u ${{ secrets.DOCKERHUBUSERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUBUSERNAME }}/miniproject:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUBUSERNAME }}/miniproject:${{ github.sha }}

