name: CI - Tests and Docker Push (no Sonar temp)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps (prod + dev)
        run: |
          pip install -r app/requirements.txt
          # dev-requirements가 없으면 pytest만 깔아준다 (안전장치)
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; else pip install pytest pytest-flask pytest-cov; fi

      - name: Ensure package import works
        run: |
          # app/__init__.py 없으면 만들어준다 (ModuleNotFoundError 예방)
          [ -f app/__init__.py ] || touch app/__init__.py

      - name: Run tests with coverage
        run: pytest app/tests/ --maxfail=1 --disable-warnings -q

      - name: Docker info (debug)
        run: docker version

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/miniproject:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/miniproject:${{ github.sha }}

