name: CI - Tests and Docker Push

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install -r app/requirements.txt
          # dev-requirements 없으면 기본 테스트 패키지 설치
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; else pip install pytest pytest-flask pytest-cov; fi
          # 패키지 인식 문제 예방
          [ -f app/__init__.py ] || touch app/__init__.py

      - name: Run tests
        run: pytest app/tests/ --maxfail=1 --disable-warnings -q

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUBTOKEN }} | docker login -u ${{ secrets.DOCKERHUBUSERNAME }} --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUBUSERNAME }}/miniproject:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUBUSERNAME }}/miniproject:${{ github.sha }}

